on: [push]
name: Linux_Container_Workflow

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hellofiber:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hellofiber:${{ github.sha }} 
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USERNAME }}
            password: ${{ secrets.VM_PASSWORD }}
            script: |
              docker-compose up -d   
        
